FROM registry.cosec.tech:5000/abfuzz-javafuzz-java-linux-amd64-ubuntu-20_04:base

# jdk environment
RUN mkdir -p /WORK
ADD jdk-8u351-linux-x64.tar.gz /WORK
ENV JAVA_HOME=/WORK/jdk1.8.0_351
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH=$JAVA_HOME/bin:/java:$PATH
