pipeline {
    agent none
    stages {
        stage('Prepare') {
            steps {
                sh 'mv data-collection-agent-1.0.0.jar docker-images/abfuzz-javafuzz-java/linux-amd64-ubuntu-20_04/${data-collection-agent-1.0.0.jar}'
                sh 'll docker-images/abfuzz-javafuzz-java/linux-amd64-ubuntu-20_04'
            }
        }
        stage('openjdk-8 Build') {
            agent {
                // Equivalent to "docker build -f docker-images/abfuzz-javafuzz-java/linux-amd64-ubuntu-20_04/Dockerfile-build --build-arg IMAGE_BASE=registry.cosec.tech:5000/abfuzz-javafuzz-java-linux-amd64-ubuntu-20_04 --build-arg IMAGE_TAG=openjdk-8 ./docker-images/abfuzz-javafuzz-java/linux-amd64-ubuntu-20_04"
                dockerfile {
                    filename 'Dockerfile-build'
                    dir 'docker-images/abfuzz-javafuzz-java/linux-amd64-ubuntu-20_04'
                    additionalBuildArgs  '--build-arg IMAGE_BASE=registry.cosec.tech:5000/abfuzz-javafuzz-java-linux-amd64-ubuntu-20_04'
                    additionalBuildArgs  '--build-arg IMAGE_TAG=openjdk-8'
                }
            }
            steps {
                echo 'Push'
                sh 'docker inspect registry.cosec.tech:5000/abfuzz-javafuzz-java-linux-amd64-ubuntu-20_04-openjdk-8 -f "{{.Id}} {{.RepoTags}}"'
                sh 'docker push registry.cosec.tech:5000/abfuzz-javafuzz-java-linux-amd64-ubuntu-20_04-openjdk-8'
            }
        }
        stage('Push') {
        }
    }
}
