pipeline {
  agent any
  tools { go '1.17.6' }

  stages {
    stage('build') {
      steps {
        sh 'echo "build starting"'
        sh 'go version'
        sh './service-go/cmd/xbuild.sh'
        //dir('service-go/cmd') {
        //    echo '2'
          //  sh 'go run main.go'
        //}
      }
    }
    stage('execute') {
      steps {
        echo 'done'
      }
    }
  }
}
