pipeline {
  agent any
  tools { go '1.17.6' }

  stages {
    stage('Build') {
      steps {
        echo 'build starting'
        sh 'go version'
        sh 'service-go/cmd/xbuild.sh'
        echo 'build done'
      }
    }
    stage('Run') {
      steps {
        //sh "nohup go run service-go/cmd/main.go 2>&1 &"
        echo 'done'
      }
    }
  }
}
