pipeline {
  agent { label '10.1.1.15' }
  tools { go '1.17.6' }

  stages {
    stage('Build') {
      steps {
        echo 'build start'
        sh 'go version'
        dir('service-go/cmd') {
            sh 'go version'
            //sh 'env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build'
            sh 'sh ./xbuild.sh'
            sh 'mv cmd /root'
            echo 'build done'
        }
        echo 'build all done'
      }
    }

    stage('Run') {
      steps {
        echo 'done'
      }
    }
  }
}
